### ISSUE TITLE
[Bug] Potential crash when using LLVM 18 or newer

### ISSUE THREAD

**Issue by pingdoom** [shenjunjiekoda/knight#4]
The current version of the knight project has an issue when using LLVM 18 or newer versions. When building knight with the latest LLVM, it can result in a crash due to a known issue in LLVM's CommandLine library.

## Description
The knight project is using LLVM's CommandLine library to handle command line options. However, there is a known issue in LLVM 18 and newer versions where the `Option` class can be registered more than once, leading to a crash.

This issue is described in the LLVM bug tracker: [CommandLine Error: Option 'experimental-debuginfo-iterators' registered more than once!](https://bugs.llvm.org/show_bug.cgi?id=50099)

## Steps to Reproduce
1. Build LLVM 18 or newer from source.
2. Build the knight project using the newly built LLVM.
3. Run the knight tool.

The tool will crash with an error similar to:
```
CommandLine Error: Option 'experimental-debuginfo-iterators' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
[1]    26042 abort
```

## Impact
This issue makes it difficult for users to build and use the knight project with the latest LLVM versions, as it will result in a crash. This can severely limit the adoption and usability of the tool.

## Proposed Solution
To fix this issue, the knight project should update the way it links against LLVM. Instead of linking against the LLVM static libraries, it should link against the LLVM dynamic library (`libLLVM.so`). This should resolve the issue with the CommandLine library.

The steps to update the knight project would be:
1. Modify the CMake scripts to allow linking against the LLVM dynamic library.
2. Update the installation script and documentation to recommend using the LLVM dynamic library for building knight.
3. Add a troubleshooting section in the documentation to address this issue and provide the solution.

## Acceptance Criteria
- The knight project can be built and used without crashing when using LLVM 18 or newer versions.
- The documentation and installation scripts are updated to reflect the recommended way of building knight with the latest LLVM versions.
- The troubleshooting section in the documentation addresses the CommandLine issue and provides the solution.

**Comment by shenjunjiekoda** [comment]
fixed in 1fc462f
